/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import proyecto.Entrada;

/**
 *
 * @author aliso
 */
public class PantallaParqueo extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaParqueo.class.getName());

    private Entrada entrada;
    private Parqueo parqueo;

    /**
     * Creates new form PantallaParqueo
     */
    public PantallaParqueo(Parqueo parqueo, Entrada entrada) {
        initComponents();
        this.parqueo = parqueo;
        this.entrada = entrada;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel1 = new javax.swing.JPanel();
        estadoParqueo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLiberar = new javax.swing.JButton();
        btnAsignar = new javax.swing.JButton();
        idSocioTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tipoSocioCombo = new javax.swing.JComboBox<>();
        MenuPrincipalParqueo1 = new javax.swing.JButton();
        asignacionSocio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        estadoParqueo.setBackground(new java.awt.Color(255, 204, 102));
        estadoParqueo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        estadoParqueo.setText("Ver Estado del Parqueo");
        estadoParqueo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 51), 4, true));
        estadoParqueo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        estadoParqueo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoParqueoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEMA DE PARQUEO SMARTFIT");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 102));
        jLabel3.setText("Codigo");

        btnLiberar.setBackground(new java.awt.Color(255, 204, 102));
        btnLiberar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLiberar.setText("Liberar");
        btnLiberar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiberarActionPerformed(evt);
            }
        });

        btnAsignar.setBackground(new java.awt.Color(255, 204, 102));
        btnAsignar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAsignar.setText("Asignar");
        btnAsignar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 102));
        jLabel4.setText("Tipo");

        tipoSocioCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comun", "Discapacitado", "Entrenador" }));
        tipoSocioCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoSocioComboActionPerformed(evt);
            }
        });

        MenuPrincipalParqueo1.setBackground(new java.awt.Color(255, 204, 102));
        MenuPrincipalParqueo1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        MenuPrincipalParqueo1.setText("Volver al Menu Principal");
        MenuPrincipalParqueo1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 51), 4, true));
        MenuPrincipalParqueo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuPrincipalParqueo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPrincipalParqueo1ActionPerformed(evt);
            }
        });

        asignacionSocio.setBackground(new java.awt.Color(255, 204, 102));
        asignacionSocio.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        asignacionSocio.setText("Asignacion por Socio");
        asignacionSocio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 51), 4, true));
        asignacionSocio.setBorderPainted(false);
        asignacionSocio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        asignacionSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignacionSocioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(262, 262, 262))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(40, 40, 40))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(jLabel4)
                                .addGap(62, 62, 62)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(tipoSocioCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLiberar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(idSocioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(110, 110, 110)
                                    .addComponent(btnAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(339, 339, 339)
                                .addComponent(asignacionSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(MenuPrincipalParqueo1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(estadoParqueo, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(idSocioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tipoSocioCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(164, 164, 164))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnLiberar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoParqueo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MenuPrincipalParqueo1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asignacionSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void estadoParqueoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoParqueoActionPerformed
        // 1. Obtiene la cadena de texto de la matriz del parqueo.
        String estadoParqueo = parqueo.mostrarEstadoParqueo();

        // 2. Crea un JTextArea para mostrar la matriz.
        JTextArea textArea = new JTextArea(20, 40);
        textArea.setText(estadoParqueo);
        textArea.setEditable(false); // Evita que el usuario edite el texto

        // 3. Agrega el JTextArea a un JScrollPane para que sea desplazable.
        JScrollPane scrollPane = new JScrollPane(textArea);

        // 4. Muestra la matriz en una ventana emergente de JOptionPane.
        JOptionPane.showMessageDialog(this, scrollPane, "Estado Actual del Parqueo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_estadoParqueoActionPerformed

    private void btnLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarActionPerformed

        // 1. Get the socio's ID from the text field.
        String idSocioStr = idSocioTxt.getText().trim();
        if (idSocioStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese el código del socio.", "Campo Vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int idSocio = Integer.parseInt(idSocioStr);
            if (parqueo.liberarEspacio(idSocio)) {
                JOptionPane.showMessageDialog(this, "Espacio liberado con éxito!");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: El ID del socio debe ser un número.", "Error de Entrada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLiberarActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        String idSocioStr = idSocioTxt.getText().trim();
        if (idSocioStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese el código del socio.", "Campo Vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int idSocio = Integer.parseInt(idSocioStr);
            String tipo = (String) tipoSocioCombo.getSelectedItem();
            boolean esDiscapacitado = tipo.equals("Discapacitado");
            boolean esEntrenador = tipo.equals("Entrenador");

            if (parqueo.asignarEspacio(idSocio, esDiscapacitado, esEntrenador)) {
                JOptionPane.showMessageDialog(this, "Espacio asignado con éxito!");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: El ID del socio debe ser un número.", "Error de Entrada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void MenuPrincipalParqueo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPrincipalParqueo1ActionPerformed
        entrada.setVisible(true);

        // Oculta la ventana actual de parqueo para que los datos persistan
        this.setVisible(false);
    }//GEN-LAST:event_MenuPrincipalParqueo1ActionPerformed

    private void asignacionSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignacionSocioActionPerformed
        String idSocioStr = JOptionPane.showInputDialog(this, "Ingrese el código del socio para buscar su espacio:", "Buscar Socio", JOptionPane.QUESTION_MESSAGE);
    
    if (idSocioStr != null && !idSocioStr.trim().isEmpty()) {
        try {
            int idSocio = Integer.parseInt(idSocioStr);
            
            // Buscar la ubicación del socio en el parqueo
            int[] ubicacion = parqueo.buscarUbicacionSocio(idSocio);
            
            if (ubicacion != null) {
                // Obtener los datos del socio desde la clase Socio
                Socio socio = Socio.buscarSocioPorCodigo(idSocio);
                String nombreSocio = (socio != null) ? socio.getNombre() : "Nombre no encontrado";
                
                String mensaje = String.format(
                    "Información del Socio y su Espacio:\n\n" +
                    "Nombre: %s\n" +
                    "Código: %d\n" +
                    "Ubicación del Espacio: Nivel G%d, Fila %d, Columna %d",
                    nombreSocio, 
                    idSocio, 
                    ubicacion[0], 
                    ubicacion[1], 
                    ubicacion[2]
                );
                
                JOptionPane.showMessageDialog(this, mensaje, "Socio Encontrado", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "El socio no tiene un espacio asignado o el código es incorrecto.", "Socio no Encontrado", JOptionPane.WARNING_MESSAGE);
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: El código debe ser un número entero.", "Error de Entrada", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_asignacionSocioActionPerformed

    private void tipoSocioComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoSocioComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoSocioComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Crea y muestra el formulario */
        java.awt.EventQueue.invokeLater(() -> {
            Parqueo parqueo = new Parqueo();
            Entrada entrada = new Entrada(parqueo); // Asegúrate de que tu clase Entrada tiene un constructor que acepta Parqueo
            new PantallaParqueo(parqueo, entrada).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MenuPrincipalParqueo1;
    private javax.swing.JButton asignacionSocio;
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnLiberar;
    private javax.swing.JButton estadoParqueo;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JTextField idSocioTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> tipoSocioCombo;
    // End of variables declaration//GEN-END:variables
}
