/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import proyecto.Socio;
import proyecto.Socio;

/**
 *
 * @author alons
 */
public class Socios extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Socios.class.getName());

    private JTextArea areaSocios;
    private JFrame menuPrincipal; // referencia al menú principal

    // Constructor recibe el menú principal
    public Socios(JFrame menuPrincipal) {
        this.menuPrincipal = menuPrincipal;

        // Aquí cargamos los socios antes de mostrarlos
        Socio.cargarSocios();

        setTitle("Lista de Socios");
        setSize(700, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());
        this.setLocationRelativeTo(null);

        JTextArea sociosArea = new JTextArea();
        sociosArea.setEditable(false);
        sociosArea.setBackground(Color.BLACK);
        sociosArea.setForeground(Color.ORANGE);//x amarillo

        // Mostrar los socios cargados
        for (int i = 0; i < Socio.numSociosActuales; i++) {
            Socio s = Socio.socios[i];
            if (s != null) {
                sociosArea.append("Nombre: " + s.getNombre()
                        + ", Código: " + s.getCodigo()
                        + ", Membresía: " + (s.isMembresia() ? "Activa" : "Inactiva")
                        + "\n");
            }
        }

        JScrollPane scrollPane = new JScrollPane(sociosArea);
        add(scrollPane, BorderLayout.CENTER);

        JButton volverBtn = new JButton("Volver al menú");
        volverBtn.setBackground(Color.ORANGE);
        volverBtn.setForeground(Color.BLACK);
        volverBtn.addActionListener(e -> {
            this.dispose();
            if (menuPrincipal != null) {
                menuPrincipal.setVisible(true);
            }
        });

        add(volverBtn, BorderLayout.SOUTH);
    }

    /**
     * Creates new form Socios
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Socios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Socio.cargarSocios();

        // Crear un menú de ejemplo
        JFrame menu = new JFrame("Menú Principal");
        menu.setSize(400, 300);
        menu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        menu.setLocationRelativeTo(null);

        JButton abrirSocios = new JButton("Abrir lista de socios");
        abrirSocios.addActionListener(e -> {
            menu.setVisible(false);
            new Socios(menu).setVisible(true);
        });

        menu.add(abrirSocios);
        menu.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
